#!/bin/bash


        Encode () {

        declare -A Flip[$((A++))]='\\'x{{0..9},{a..f}}{{0..9},{a..f}}
        declare -a Side=($(eval echo -e \${Flip[{0..255}]/\#/'\\'}))
        declare -a Side=(${Side[@]//[![:print:]]})
        Side=(${Side[@]//['\\'|\*]}) && Side+=('\' '\*')
        declare -A Down[\\${Side[B++]}]={00..98}
        echo ${#Side[@]}

                for Right in $@; do
                echo ${Down[$Right]}
                Left+=(${Down[$Right]})
                done

        }

Encode ${@//?()/\\} && echo ${Left[@]}
